name: roastyourex
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  rive: ^0.10.4
  flutter_svg: ^2.0.5
  firebase_auth: ^4.6.0
  flutter_facebook_auth: ^5.0.11
  firebase_core: ^2.12.0
  google_sign_in: ^6.1.0
  social_login_buttons: ^1.0.7
  hexcolor: ^3.0.1
  image_picker: ^0.8.7+5
  awesome_dialog: ^2.2.1
  otp_text_field: ^1.1.3
  theme_provider: ^0.6.0
  get: ^4.6.5
  flutter_staggered_animations: ^1.1.1
  provider: ^6.0.5
  fluttertoast: ^8.2.1
  github_sign_in_plus: ^0.0.2
  sqflite: ^2.2.8+2
  cloud_firestore: ^4.7.0
  firebase_storage: ^11.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/icons/
    - assets/RiveAssets/
